### PR TITLE
Display attack data

### PR DESCRIPTION
**Pull request by sammygutierrez**
This makes it a bit easier to see how much damage has been done when comparing hits/combos.

https://user-images.githubusercontent.com/2582590/151533932-0ab5cdb2-27a7-4e48-9ae6-8fa516101440.mp4

### CODE REVIEW

**Comment by migeru-san** [comment]
can you do it like this? without overlapping the other modules? doesn't need to be huge but small and in the center perhaps

Screen Shot 2022-02-14 at 2 11 54 PM

**Comment by migeru-san** [comment]
The total damage is cool but I think is more useful to see how much each combo damage, then it resets to 0 when another combo starts

If you can add the stun and total combo to reset each time will be nice

**Comment by sammygutierrez** [comment]
@migeru-san Good suggestion, I was thinking of something similar. 

I've added a rough initial implementation to display additional attack data to this pull request. We can read the combo counter from the game's memory and determine the attack data based on that number. However this isn't perfect (you might see some inaccurate data like negative numbers for the stun and meter) but I think it's a good start. :)

https://user-images.githubusercontent.com/2582590/154662797-1f51a4ba-7e87-4159-a368-9b05299b4daf.mp4

**Comment by sammygutierrez** [comment]
Updated implementation to be more accurate by reading hit damage and stun data from the game instead of doing calculating from the life/stun bars.

https://user-images.githubusercontent.com/2582590/154825359-15fb02e1-966d-450f-8017-b4d062de16e2.mp4

**Comment by migeru-san** [comment]
The latest one looks more accurate, I will test some more. great job!

**Comment by Grouflon** [comment]
It is merged. That's awesome work, thanks you so much!

**Pull request merged**
